// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/boreq/bolt-ui/adapters"
	"github.com/boreq/bolt-ui/application"
	"github.com/boreq/bolt-ui/internal/config"
	"github.com/boreq/bolt-ui/internal/service"
	"github.com/boreq/bolt-ui/ports/http"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func BuildTransactableAdapters(tx *bbolt.Tx) (*application.TransactableAdapters, error) {
	database := adapters.NewDatabase(tx)
	transactableAdapters := &application.TransactableAdapters{
		Database: database,
	}
	return transactableAdapters, nil
}

func BuildTestTransactableAdapters(tx *bbolt.Tx, mocks Mocks) (*application.TransactableAdapters, error) {
	database := adapters.NewDatabase(tx)
	transactableAdapters := &application.TransactableAdapters{
		Database: database,
	}
	return transactableAdapters, nil
}

func BuildApplicationForTest(db *bbolt.DB) (TestApplication, error) {
	mocks := Mocks{}
	wireTestAdaptersProvider := newTestAdaptersProvider(mocks)
	transactionProvider := adapters.NewTransactionProvider(db, wireTestAdaptersProvider)
	browseHandler := application.NewBrowseHandler(transactionProvider)
	applicationApplication := &application.Application{
		Browse: browseHandler,
	}
	testApplication := TestApplication{
		Application: applicationApplication,
		Mocks:       mocks,
		DB:          db,
	}
	return testApplication, nil
}

func BuildService(conf *config.Config) (*service.Service, error) {
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAdaptersProvider := newAdaptersProvider()
	transactionProvider := adapters.NewTransactionProvider(db, wireAdaptersProvider)
	browseHandler := application.NewBrowseHandler(transactionProvider)
	applicationApplication := &application.Application{
		Browse: browseHandler,
	}
	tokenAuthProvider := http.NewTokenAuthProvider(conf)
	handler, err := http.NewHandler(applicationApplication, tokenAuthProvider, conf.EncodingCBOR)
	if err != nil {
		return nil, err
	}
	server := http.NewServer(handler, conf)
	serviceService := service.NewService(server)
	return serviceService, nil
}

// wire.go:

type TestApplication struct {
	Application *application.Application
	Mocks
	DB *bbolt.DB
}

type Mocks struct {
}
